/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mars.rover

/*
 * Mars Rover on a rectangular plateau
 * Current position is defined by coordinates (x,y) and heading (N,S,E,W)
 * In order to move the rover, you must give it L, R, M
 * L -> Turns left
 * R -> Turns right
 * M -> Moves one in the direction it's facing
 */


/*
 * Rover moves on a plateau
 * Rover takes in commands
 * Rover outputs current position
 */

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
}
